### ISSUE TITLE
Ausleihstatus ist falsch

### ISSUE THREAD

**Issue by ZugBahnHof** [Katharineum/tinventory#9]
![Bildschirmfoto von 2019-12-06 15-20-00](https://user-images.githubusercontent.com/29484395/70329546-f7ef1780-183b-11ea-93f2-df527d07b1d2.png)
![Bildschirmfoto von 2019-12-06 15-19-50](https://user-images.githubusercontent.com/29484395/70329547-f7ef1780-183b-11ea-9cd5-ff40751a7e51.png)

Beide Bilder wurden zur gleichen Zeit aufgenommen.

**Comment by hansegucker** [comment]
Simple issue: 
![grafik](https://user-images.githubusercontent.com/24552951/86515826-22c63c00-be1c-11ea-8586-cc65c593975c.png)
